import raw from './directories.json';

/**
 * Seedit's short routes (/s/news, /s/pics…): a code several communities
 * compete for, resolved by Seedit to the top-ranked candidate of the published
 * list. Posts never live under a code (their URL is /c/<cid>); the archive's
 * /s/<code> page lists posts from every community that has competed for it.
 *
 * `directories.json` is generated by `scripts/build-communities.mjs` from
 * bitsocialnet/lists — don't hand-edit it.
 */
export interface Directory {
  /** The short route: "news" for /s/news. */
  code: string;
  /** Display title from seedit-directories-defaults.json, e.g. "News". */
  title: string;
  description?: string;
  tags?: string[];
  /** Candidates listed today, in Seedit's rank order: boards[0] is the code's current winner. */
  boards: string[];
  /** Communities once listed under the code and dropped since; their posts stay on its page. */
  former: string[];
}

type RawDirectory = Omit<Directory, 'former'> & { former?: string[] };

/** In Seedit's own order (its default subscriptions); codes that left the lists come last. */
export const directories: Directory[] = (raw as RawDirectory[]).map((d) => ({ ...d, former: d.former ?? [] }));

const byCode = new Map(directories.map((d) => [d.code, d]));

export const getDirectory = (code: string): Directory | null => byCode.get(code) ?? null;

/** Every community archived under a code: the listed ones first, then the former ones. */
export const archivedBoards = (dir: Directory): string[] => [...dir.boards, ...dir.former];

// A community listed under one code today and formerly under another belongs to
// the code that lists it now; former memberships only fill gaps.
const byAddress = new Map<string, Directory>();
for (const pick of [(d: Directory) => d.boards, (d: Directory) => d.former]) {
  for (const dir of directories) {
    for (const address of pick(dir)) if (!byAddress.has(address)) byAddress.set(address, dir);
  }
}

export const directoryForAddress = (address: string): Directory | null => byAddress.get(address) ?? null;

export const DIRECTORY_INDEX_PATH = '/communities/directories';
export const codePath = (code: string) => `/s/${encodeURIComponent(code)}`;
export const directoryListPath = (code: string) => `${DIRECTORY_INDEX_PATH}/${encodeURIComponent(code)}`;
export const seeditCodeUrl = (code: string) => `https://seedit.app/#/s/${encodeURIComponent(code)}`;
